knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_SECRET)%'
            redirect_route: google_connect_check
        azure:
            type: azure
            client_id: '%env(OAUTH_AZURE_ID)%'
            client_secret: '%env(OAUTH_AZURE_SECRET)%'
            redirect_route: azure_connect_check
